export const products = [
  {
    name: "Product 1",
    image: "p1.jpg",
    price: 19.99,
    quantity: 0,
  },
  {
    name: "Product 2",
    image: "p2.jpg",
    price: 11,
    quantity: 0,
  },
  {
    name: "Product 3",
    image: "p3.jpg",
    price: 1.99,
    quantity: 0,
  },
  {
    name: "Product 4",
    image: "p4.jpg",
    price: 1300,
    quantity: 0,
  },
  {
    name: "Product 5",
    image: "p5.jpg",
    price: 19,
    quantity: 0,
  },
  {
    name: "Product 6",
    image: "p6.jpg",
    price: 90,
    quantity: 0,
  },
  {
    name: "Product 7",
    image: "p7.jpg",
    price: 111,
    quantity: 0,
  },
  {
    name: "Product 8",
    image: "p8.png",
    price: 199,
    quantity: 0,
  },
  {
    name: "Product 9",
    image: "p9.jpg",
    price: 911,
    quantity: 0,
  },
  {
    name: "Product 10",
    image: "p10.jpg",
    price: 91,
    quantity: 0,
  },
  {
    name: "Product 11",
    image: "p11.jpg",
    price: 87,
    quantity: 0,
  },
  {
    name: "Product 12",
    image: "p12.jpg",
    price: 33,
    quantity: 0,
  },
  {
    name: "Product 113",
    image: "p1.jpg",
    price: 19.99,
    quantity: 0,
  },
  {
    name: "Product 14",
    image: "p2.jpg",
    price: 11,
    quantity: 0,
  },
  {
    name: "Product 15",
    image: "p3.jpg",
    price: 1.99,
    quantity: 0,
  },
  {
    name: "Product 16",
    image: "p4.jpg",
    price: 1300,
    quantity: 0,
  },
  {
    name: "Product 5",
    image: "p5.jpg",
    price: 19,
    quantity: 0,
  },
  {
    name: "Product 6",
    image: "p6.jpg",
    price: 90,
    quantity: 0,
  },
  {
    name: "Product 7",
    image: "p7.jpg",
    price: 111,
    quantity: 0,
  },
  {
    name: "Product 8",
    image: "p8.png",
    price: 199,
    quantity: 0,
  },
  {
    name: "Product 9",
    image: "p9.jpg",
    price: 911,
    quantity: 0,
  },
  {
    name: "Product 10",
    image: "p10.jpg",
    price: 91,
    quantity: 0,
  },
  {
    name: "Product 11",
    image: "p11.jpg",
    price: 87,
    quantity: 0,
  },
  {
    name: "Product 12",
    image: "p12.jpg",
    price: 33,
    quantity: 0,
  },
  {
    name: "Product 8",
    image: "p8.png",
    price: 199,
    quantity: 0,
  },
  {
    name: "Product 9",
    image: "p9.jpg",
    price: 911,
    quantity: 0,
  },
  {
    name: "Product 10",
    image: "p10.jpg",
    price: 91,
    quantity: 0,
  },
  {
    name: "Product 11",
    image: "p11.jpg",
    price: 87,
    quantity: 0,
  },
  {
    name: "Product 12",
    image: "p12.jpg",
    price: 33,
    quantity: 0,
  },
];
